[api]
enabled = true

[functions.line-register]
import_map = "functions/deno.json"

[functions.create-checkout-session]
import_map = "functions/deno.json"

[functions.stripe-webhook]
import_map = "functions/deno.json"
